name: .NET Core

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com/garythemann/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
       nuget-version: latest

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build

    - name: Publish the package to GitHub Packages
      run: |
        echo "<configuration />" > nuget.config
        nuget source add -Name "GPR" \
                         -Source https://nuget.pkg.github.com/${{ github.actor }}/index.json \
                         -UserName ${{ github.actor }} \
                         -Password ${{ secrets.GITHUB_TOKEN }} \
                         -ConfigFile nuget.config \
                         -StorePasswordInClearText
        dotnet nuget push ./bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.actor }}/index.json"
