name: .NET Core

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com/garythemann/index.json

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
       nuget-version: latest

    - name: Restore
      run: make dotnet/restore

    - name: Build
      run: make -- -dotnet/build

    - name: Pack
      run: make -- -dotnet/pack

    - name: Publish the package to GitHub Packages
      run: make dotnet/push
      env:
        NUGET_SOURCE_URL: https://nuget.pkg.github.com/${{ github.actor }}/index.json
        NUGET_USER_NAME: ${{ github.actor }}
        NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
